version: "3.8"

services:
  master:
    build:
      context: .  # Usa il contesto della directory radice
      dockerfile: ./master/Dockerfile
    container_name: master
    ports:
      - "8080:8080"
    networks:
      - app_network
    environment:
      - MASTER_NAME=master
    command: ["./master/master"]

  worker-1:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    container_name: worker-1
    environment:
      - WORKER_ID=1
    networks:
      - app_network
    command: ["./worker/worker", "-ID=1"]

  worker-2:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    container_name: worker-2
    environment:
      - WORKER_ID=2
    networks:
      - app_network
    command: ["./worker/worker", "-ID=2"]

  worker-3:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    container_name: worker-3
    environment:
      - WORKER_ID=3
    networks:
      - app_network
    command: ["./worker/worker", "-ID=3"]

  worker-4:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    container_name: worker-4
    environment:
      - WORKER_ID=4
    networks:
      - app_network
    command: ["./worker/worker", "-ID=4"]

  worker-5:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    container_name: worker-5
    environment:
      - WORKER_ID=5
    networks:
      - app_network
    command: ["./worker/worker", "-ID=5"]

  client:
    build:
      context: .  # Usa il contesto della directory radice
      dockerfile: ./client/Dockerfile
    container_name: client
    networks:
      - app_network
    depends_on:
      - master
    command: ["./client/client"]

networks:
  app_network:
    driver: bridge